const images=[['FAITH V5 #1.jpg','Faith'],['IT GOAT V2.jpg','It Goat'],['THE PROBLEM V2 #1.jpg','The Problem'],['ONE C #4.jpg','One C'],['GYM STYLES P4 #2.jpg','Gym Styles'],['IT EFFECT #1.jpg','It Effect'],['STAR V3 #1.jpg','Star'],['BEST TRAITS #2.jpg','Best Traits'],['WYST #6.jpg','WYST'],['TAIRA #6.jpg','Taira']];
const socialAds=[['FLOWLY AD 1.mp4','Flowly Ad 01','1bHG7D0BKitvvez17-9krv4rONpVPuncx'],['FLOWLY AD 2.mp4','Flowly Ad 02','1zC1O13ouRskELnkVr_HCRlEQAxHQxh-J'],['FLOWLY AD 3.mp4','Flowly Ad 03','1CLEfRLIHs3CtkXcM-Qv0coNCAaGVEDpb'],['FLOWLY AD 4.mp4','Flowly Ad 04','1SVzIV8gDhpTJ84gL9WmngS5L_VA1Ls86'],['FLOWLY AD 5.mp4','Flowly Ad 05','1Z3q5aaLQVkA35Pu6JIAbnTZwBxK8e8Cv'],['FLOWLY AD 6.mp4','Flowly Ad 06','1tJlsieXhaxWQFDDVDegK-1tVx_b9Pl-B'],['FLOWLY AD 7.mp4','Flowly Ad 07','1fgnDMm0ys6QjvIWFc8mmEX9t2eowpN9X'],['FLOWLY AD 8.mp4','Flowly Ad 08','1ZAmjGOd30Mq2XyUGtZSWqb7FFTTqGlGU'],['FLOWLY AD 9.mp4','Flowly Ad 09','1jtYc8Xq_AJIcyOU_LLcaaw_xI00RVIHF']];
const youtubeVideos=[['Map Zoom.mp4','Map zoom','1YaHbSMDuhHq70l1PkJgk3_FX5E-v_waa'],["Jay_s Noodle Rant.mp4","Jay’s noodle rant",'1mcKZ59OVugtzWaxv5EfVXpXwZx5T58DY'],["Bernardo_s Gym Routine.mp4","Bernardo’s gym routine",'1jylkGpLkesFLDgRxrUwspQ9d9xf9J8Wy'],['Green Screen No Key.mp4','Green screen','1RmfyTNZ1Pq8M-Ro13EP5RgSHwrs5wl_e']];
const misc=[['ACR B&W.jpg','ACR / identity'],['SAINTCORE LOGO V.jpg','Saintcore / logo'],['AGNUS DEI BLUE.jpg','Agnus Dei'],['JAPANESE LANDSCAPE V3.jpg','Japanese landscape'],['JPII 1.1.jpg','JPII'],['ROAD TRIP 2.jpg','Road trip / 02'],['JAPANESE LANDSCAPE.jpg','Japanese landscape / 02']];
const enc=v=>encodeURIComponent(v), imagePath=n=>n==='FAITH V5 #1.jpg'?'site-assets/stable/faith.jpg':`site-assets/thumbs/${enc(n)}`, miscPath=n=>n==='AGNUS DEI BLUE.jpg'?'https://raw.githubusercontent.com/SamStace/workaway-portfolio/1583aa3a0e8333f9b775a1c6f419898ffa31042/site-assets/stable/agnus-dei-source.jpg':`site-assets/misc/${enc(n)}`, drivePath=id=>`https://drive.google.com/file/d/${id}/preview`;
const imageGrid=document.querySelector('#image-grid'), videoGrid=document.querySelector('#video-grid'), youtubeGrid=document.querySelector('#youtube-grid'), miscGrid=document.querySelector('#misc-grid'), dialog=document.querySelector('#media-dialog'), dialogContent=document.querySelector('#dialog-content');
images.forEach(([file,label],i)=>imageGrid.insertAdjacentHTML('beforeend',`<figure class="image-tile" data-type="image" data-src="${imagePath(file)}" data-label="${label}"><img loading="lazy" src="${imagePath(file)}" alt="${label} — selected work" /><figcaption class="tile-meta"><span>${String(i+1).padStart(2,'0')} / ${label}</span><span>↗</span></figcaption></figure>`));
const renderVideos=(list,target)=>list.forEach(([file,label,id],i)=>{const thumb=label==='Flowly Ad 04'?'site-assets/stable/flowly-ad-04.jpg':`https://drive.google.com/thumbnail?id=${id}&sz=w1000`; target.insertAdjacentHTML('beforeend',`<figure class="video-tile" data-type="drive-video" data-src="${drivePath(id)}" data-label="${label}"><div class="video-poster"><img src="${thumb}" alt="${label}" loading="lazy" /><div class="drive-play">▶</div></div><figcaption>${label}<span>${String(i+1).padStart(2,'0')} / Drive</span></figcaption></figure>`)});
renderVideos(socialAds,videoGrid); renderVideos(youtubeVideos,youtubeGrid);
misc.forEach(([file,label],i)=>miscGrid.insertAdjacentHTML('beforeend',`<figure class="image-tile" data-type="image" data-src="${miscPath(file)}" data-label="${label}"><img loading="lazy" src="${miscPath(file)}" alt="${label}" /><figcaption class="tile-meta"><span>${String(i+15).padStart(2,'0')} / ${label}</span><span>↗</span></figcaption></figure>`));
document.querySelectorAll('[data-type]').forEach(tile=>tile.addEventListener('click',()=>{const isVideo=tile.dataset.type==='video',isDrive=tile.dataset.type==='drive-video';dialogContent.innerHTML=isDrive?`<iframe class="drive-frame" src="${tile.dataset.src}" allow="autoplay; fullscreen" allowfullscreen title="${tile.dataset.label}"></iframe><div class="dialog-caption">${tile.dataset.label} · <a href="${tile.dataset.src.replace('/preview','/view?usp=sharing')}" target="_blank" rel="noreferrer">Open in Google Drive ↗</a></div>`:isVideo?`<video controls autoplay playsinline src="${tile.dataset.src}"></video><div class="dialog-caption">${tile.dataset.label}</div>`:`<img src="${tile.dataset.src}" alt="${tile.dataset.label}" /><div class="dialog-caption">${tile.dataset.label}</div>`;dialog.showModal()}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close()); dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});

